### ISSUE TITLE
How to start the Activity?

### ISSUE THREAD

**Issue by alexandre-mbm** [johnroyer/FileManagrPlus-translation#11]
Sorry. I know here is not right site for this. But I want too much to start FileManager+'s Activity at directory. How to do it?

**Comment by johnroyer** [comment]
You can go to the main page at Google Play: https://play.google.com/store/apps/details?id=com.alphainventor.filemanager

At the bottom, you can find support email. Contact the develop team via the email: support@androidpub.com

**Comment by alexandre-mbm** [comment]
Based on:
`V/Activity(20718): startActivity for intent Intent { act=com.alphainventor.filemanager.OPEN_FILE dat=main://0/storage/emulated/0/WhatsApp/Media/WhatsApp Video flg=0x34000000 cmp=com.alphainventor.filemanager/.activity.MainActivity }
^C`


From:
```sh
$ adb logcat | grep Activity | grep Intent
```

My answer:
`am start -a com.alphainventor.filemanager.OPEN_FILE -n com.alphainventor.filemanager/com.alphainventor.filemanager.activity.MainActivity -d main://0/storage/emulated/0/WhatsApp/Media --activity-clear-task`
