### ISSUE TITLE
檔案列表翻譯錯誤

### ISSUE THREAD

**Issue by johnroyer** [johnroyer/FileManagrPlus-translation#3]
![2017-09-18 14 23 25](https://user-images.githubusercontent.com/114491/30530942-82faff52-9c7d-11e7-8062-823832588663.png)

「項目」沒有翻譯到

**Comment by shininglion** [comment]
我確認了一下，目前沒有地方是沒有翻譯到的，這會不會是你自己本身的資料夾? 是的話不可能有對應翻譯的

**Comment by johnroyer** [comment]
資料夾底下有幾個「項目」，這個詞應該和我本身的手機設定沒有關係的說。

有沒有可能是 nightly build failed ?  XD

**Comment by shininglion** [comment]
原來你是指那個簡體字，這個我先修改掉了

**Comment by johnroyer** [comment]
感謝，這個 issue 先麻煩你了。

**Comment by johnroyer** [comment]
我改好了，放在 branch `patch`
